use validator::ValidateEmail;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SubscriberEmail(String);

impl SubscriberEmail {
    pub fn parse(email: String) -> Result<Self, String> {
        if email.validate_email() {
            Ok(Self(email))
        } else {
            Err("Invalid email".to_string())
        }
    }
}

impl AsRef<str> for SubscriberEmail {
    fn as_ref(&self) -> &str {
        &self.0
    }
}

impl AsMut<str> for SubscriberEmail {
    fn as_mut(&mut self) -> &mut str {
        self.0.as_mut()
    }
}

#[cfg(test)]
mod tests {
    use claims::assert_err;
    use fake::{
        faker::internet::en::SafeEmail,
        rand::{rngs::StdRng, SeedableRng},
        Fake,
    };

    use super::*;

    #[derive(Debug, Clone, PartialEq, Eq)]
    struct ValidEmailFixture(pub String);

    impl quickcheck::Arbitrary for ValidEmailFixture {
        // We get `quickcheck` and `fake` to interoperate via the `rand` crate.
        // We create a seed from a random `u64` generated by `quickcheck`'s `Gen`,
        // which is in turn determined by `quickcheck`'s own seed.
        // We then use this seed to create a new random number generator, which
        // we pass to `fake`'s `SafeEmail`.
        // This way we can generate a random valid email every time `quickcheck`
        // calls `arbitrary`, and the generation process is deterministic for
        // a given seed.
        fn arbitrary(g: &mut quickcheck::Gen) -> Self {
            let mut rng = StdRng::seed_from_u64(u64::arbitrary(g));
            let email = SafeEmail().fake_with_rng(&mut rng);
            dbg!(&email);
            Self(email)
        }
    }

    #[quickcheck_macros::quickcheck]
    fn valid_emails_are_parsed_successfully(fixture: ValidEmailFixture) -> bool {
        SubscriberEmail::parse(fixture.0).is_ok()
    }

    #[test]
    fn empty_string_is_rejected() {
        let email = "".to_string();
        assert_err!(SubscriberEmail::parse(email));
    }

    #[test]
    fn email_with_invalid_characters_is_rejected() {
        let email = "test@test.com/test".to_string();
        assert_err!(SubscriberEmail::parse(email));
    }

    #[test]
    fn email_missing_subject_is_rejected() {
        let email = "@test.com".to_string();
        assert_err!(SubscriberEmail::parse(email));
    }
}
