-- Add migration script here
CREATE TABLE IF NOT EXISTS subscriptions(
  pk_subscription UUID PRIMARY KEY,
  idx_subscription BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  tx_email VARCHAR(64) UNIQUE NOT NULL,
  tx_name VARCHAR(128) NOT NULL,
  ts_created_at TIMESTAMP NOT NULL DEFAULT now(),
  ts_subscribed_at TIMESTAMP NOT NULL DEFAULT now()
);
